name = "github-starred-notify"
main = "src/worker.ts"
compatibility_date = "2023-05-15"

[[d1_databases]]
binding = "DB"
database_name = "github-starred-notify"
database_id = "REPLACE_WITH_YOUR_D1_DATABASE_ID"

# [triggers]
# crons = ["* * * * *"] # * * * * * = run every minute
